config/routes.rb
require "resque_web"
Messaging::Application.routes.draw do
  devise_for :users
  resources :rules

  resources :groups

  resources :contacts

  resources :deliverables

  resources :sms
  resources :emails
  resources :accountings

  resources :controls

  resources :customers

  match '/responses' => SmsResponse, :anchor => false, :via => :get

  match 'rules/:id/deactivate', to: 'rules#deactivate', :as => 'deactivate_rule', :via => :get
  match 'rules/:id/activate', to: 'rules#activate', :as => 'activate_rule', :via => :get
  root 'customers#index'

  mount ResqueWeb::Engine => "/scheduler"
  ResqueWeb::Engine.eager_load!
end

app/models/control.rb
# == Schema Information
#
# Table name: controls
#
#  id            :integer          not null, primary key
#  name          :string(255)
#  created_at    :datetime
#  updated_at    :datetime
#  friendly_name :string(255)
#

require 'yaml'
class Control < ActiveRecord::Base
  has_many :customers

# Create a list of all current connections
#  available in database.yml
  def self.connections
    YAML::load(File.read('config/database.yml'))
  end
end

app/controllers/controls_controller.rb
class ControlsController < ApplicationController

  load_and_authorize_resource
  before_action :set_control, only: [:show, :edit, :update, :destroy]

  # GET /controls
  # GET /controls.json
  def index
    @controls = Control.all
  end

  # GET /controls/1
  # GET /controls/1.json
  def show
  end

  # GET /controls/new
  def new
    @control = Control.new
  end

  # GET /controls/1/edit
  def edit
  end

  # POST /controls
  # POST /controls.json
  def create
    @control = Control.new(control_params)

    respond_to do |format|
      if @control.save
        format.html { redirect_to @control, notice: 'Control was successfully created.' }
        format.json { render action: 'show', status: :created, location: @control }
      else
        format.html { render action: 'new' }
        format.json { render json: @control.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /controls/1
  # PATCH/PUT /controls/1.json
  def update
    respond_to do |format|
      if @control.update(control_params)
        format.html { redirect_to @control, notice: 'Control was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @control.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /controls/1
  # DELETE /controls/1.json
  def destroy
    @control.destroy
    respond_to do |format|
      format.html { redirect_to controls_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_control
      @control = Control.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def control_params
      params.require(:control).permit(:customer_id, :name, :friendly_name)
    end
end

app/helpers/controls_helper.rb
module ControlsHelper
end

app/views/controls/_form.html.erb
<%= form_for(@control) do |f| %>
  <% if @control.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@control.errors.count, "error") %> prohibited this control from being saved:</h2>

      <ul>
      <% @control.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="field">
      <%= f.label :connections %><br>
      <%= f.select :name, Control.connections.keys {|c| [ c.humanize.capitalize, c ] } %>
    </div>
    <div class="field">
     <%= f.label :friendly_name %><br>
     <%= f.text_field :friendly_name %>
    </div>
    <div class="actions">
     <%= f.submit %>
    </div>
<% end %>

app/views/controls/edit.html.erb
<h1>Editing control</h1>

<%= render 'form' %>

<%= link_to 'Show', @control %> |
<%= link_to 'Back', controls_path %>

app/views/controls/index.html.erb
<h1>Listing controls</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @controls.each do |control| %>
      <tr>
        <td><%= control.friendly_name %></td>
        <td><%= link_to 'Show', control %></td>
        <td><%= link_to 'Edit', edit_control_path(control) %></td>
        <td><%= link_to 'Destroy', control, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Control', new_control_path %>

app/views/controls/new.html.erb
<h1>New control</h1>

<%= render 'form' %>

<%= link_to 'Back', controls_path %>

app/views/controls/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @control.name %>
</p>

<p>
  <strong>Friendly Name:</strong>
  <%= @control.friendly_name %>
</p>


<%= link_to 'Edit', edit_control_path(@control) %> |
<%= link_to 'Back', controls_path %>