config/routes.rb
require "resque_web"
Messaging::Application.routes.draw do
  devise_for :users
  resources :rules

  resources :groups

  resources :contacts

  resources :deliverables

  resources :sms
  resources :emails
  resources :accountings

  resources :controls

  resources :customers

  match '/responses' => SmsResponse, :anchor => false, :via => :get

  match 'rules/:id/deactivate', to: 'rules#deactivate', :as => 'deactivate_rule', :via => :get
  match 'rules/:id/activate', to: 'rules#activate', :as => 'activate_rule', :via => :get
  root 'customers#index'

  mount ResqueWeb::Engine => "/scheduler"
  ResqueWeb::Engine.eager_load!
end

app/models/customer.rb
# == Schema Information
#
# Table name: customers
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#  email_fee  :integer
#  sms_fee    :integer
#  send_sms   :boolean
#  send_email :boolean
#  control_id :integer
#  phone      :string(255)
#

class Customer < ActiveRecord::Base
  belongs_to :control
  has_many :deliverables
  has_many :accountings
  has_many :rules
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  load_and_authorize_resource
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
    @customer.control = Control.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @customer }
      else
        format.html { render action: 'new' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:name, :phone, :email, :twilio_api, :send_email, :send_sms, :email_fee, :sms_fee, :control_id)
    end
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :control %><br>
    <%= f.select :control_id, Control.all.map {|c| [ c.friendly_name, c.id ] } %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :email_fee %><br>
    <%= f.text_field :email_fee %>
  </div>
  <div class="field">
    <%= f.label :sms_fee %><br>
    <%= f.text_field :sms_fee %>
  </div>
  <div class="field">
    <%= f.label :send_sms %><br>
    <%= f.check_box :send_sms %>
  </div>
  <div class="field">
    <%= f.label :send_email %><br>
    <%= f.check_box :send_email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<h1>Customer Listing</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Control</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Email Fee</th>
      <th>Sms Fee</th>
      <th>Email</th>
      <th>Sms</th>
      <th>Send</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @customers.each do |customer| %>
      <tr>
        <td><%= customer.name %></td>
        <td><%= customer.control.friendly_name if customer.control.present? %></td>
        <td><%= customer.phone %></td>
        <td><%= customer.email %></td>
        <td><%= customer.email_fee %></td>
        <td><%= customer.sms_fee %></td>
        <td><%= customer.send_email %></td>
        <td><%= customer.send_sms %></td>
        <td>
          <%= link_to 'Sms', new_sms_path(:customer => customer) %>
          <%= link_to 'Email', new_email_path(:customer => customer) %>
        </td>
        <td>
           <%= link_to 'Edit', edit_customer_path(customer) %>
           <%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %>
       </td>
     </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Customer', new_customer_path %></br/>
<%= link_to 'Controls', controls_path %></br/>
<%= link_to 'Rules', rules_path %><br/>
<%= link_to 'Scheduler', '/scheduler' %>

app/views/customers/new.html.erb
<h1>New customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @customer.name %>
</p>

<p>
  <strong>Control:</strong>
  <%= @customer.control.friendly_name if @customer.control.present? %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone if @customer.phone.present? %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email if @customer.email.present? %>
</p>
<p>

  <strong>Email Fee:</strong>
  <%= @customer.email_fee %>
</p>

<p>
  <strong>Sms Fee::</strong>
  <%= @customer.sms_fee %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.send_email %>
</p>

<p>
  <strong>Sms:</strong>
  <%= @customer.send_sms %>
</p>

<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>