config/routes.rb
require "resque_web"
Messaging::Application.routes.draw do
  devise_for :users
  resources :rules

  resources :groups

  resources :contacts

  resources :deliverables

  resources :sms
  resources :emails
  resources :accountings

  resources :controls

  resources :customers

  match '/responses' => SmsResponse, :anchor => false, :via => :get

  match 'rules/:id/deactivate', to: 'rules#deactivate', :as => 'deactivate_rule', :via => :get
  match 'rules/:id/activate', to: 'rules#activate', :as => 'activate_rule', :via => :get
  root 'customers#index'

  mount ResqueWeb::Engine => "/scheduler"
  ResqueWeb::Engine.eager_load!
end

app/models/accounting.rb
# == Schema Information
#
# Table name: accountings
#
#  id          :integer          not null, primary key
#  customer_id :integer
#  invoiced    :integer
#  paid        :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Accounting < ActiveRecord::Base
  belongs_to :customer
  has_many :deliverables
end

app/controllers/accountings_controller.rb
class AccountingsController < ApplicationController
  before_action :set_accounting, only: [:show, :edit, :update, :destroy]

  # GET /accountings
  # GET /accountings.json
  def index
    @accountings = Accounting.all
  end

  # GET /accountings/1
  # GET /accountings/1.json
  def show
  end

  # GET /accountings/new
  def new
    @accounting = Accounting.new
  end

  # GET /accountings/1/edit
  def edit
  end

  # POST /accountings
  # POST /accountings.json
  def create
    @accounting = Accounting.new(accounting_params)

    respond_to do |format|
      if @accounting.save
        format.html { redirect_to @accounting, notice: 'Accounting was successfully created.' }
        format.json { render action: 'show', status: :created, location: @accounting }
      else
        format.html { render action: 'new' }
        format.json { render json: @accounting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /accountings/1
  # PATCH/PUT /accountings/1.json
  def update
    respond_to do |format|
      if @accounting.update(accounting_params)
        format.html { redirect_to @accounting, notice: 'Accounting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @accounting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /accountings/1
  # DELETE /accountings/1.json
  def destroy
    @accounting.destroy
    respond_to do |format|
      format.html { redirect_to accountings_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_accounting
      @accounting = Accounting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def accounting_params
      params.require(:accounting).permit(:customer_id, :invoiced, :paid)
    end
end

app/helpers/accountings_helper.rb
module AccountingsHelper
end

app/views/accountings/_form.html.erb
<%= form_for(@accounting) do |f| %>
  <% if @accounting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@accounting.errors.count, "error") %> prohibited this accounting from being saved:</h2>

      <ul>
      <% @accounting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :invoiced %><br>
    <%= f.text_field :invoiced %>
  </div>
  <div class="field">
    <%= f.label :paid %><br>
    <%= f.text_field :paid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accountings/edit.html.erb
<h1>Editing accounting</h1>

<%= render 'form' %>

<%= link_to 'Show', @accounting %> |
<%= link_to 'Back', accountings_path %>

app/views/accountings/index.html.erb
<h1>Listing accountings</h1>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Invoiced</th>
      <th>Paid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @accountings.each do |accounting| %>
      <tr>
        <td><%= accounting.customer_id %></td>
        <td><%= accounting.invoiced %></td>
        <td><%= accounting.paid %></td>
        <td><%= link_to 'Show', accounting %></td>
        <td><%= link_to 'Edit', edit_accounting_path(accounting) %></td>
        <td><%= link_to 'Destroy', accounting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Accounting', new_accounting_path %>

app/views/accountings/new.html.erb
<h1>New accounting</h1>

<%= render 'form' %>

<%= link_to 'Back', accountings_path %>

app/views/accountings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Customer:</strong>
  <%= @accounting.customer_id %>
</p>

<p>
  <strong>Invoiced:</strong>
  <%= @accounting.invoiced %>
</p>

<p>
  <strong>Paid:</strong>
  <%= @accounting.paid %>
</p>

<%= link_to 'Edit', edit_accounting_path(@accounting) %> |
<%= link_to 'Back', accountings_path %>