config/routes.rb
require "resque_web"
Messaging::Application.routes.draw do
  devise_for :users
  resources :rules

  resources :groups

  resources :contacts

  resources :deliverables

  resources :sms
  resources :emails
  resources :accountings

  resources :controls

  resources :customers

  match '/responses' => SmsResponse, :anchor => false, :via => :get

  match 'rules/:id/deactivate', to: 'rules#deactivate', :as => 'deactivate_rule', :via => :get
  match 'rules/:id/activate', to: 'rules#activate', :as => 'activate_rule', :via => :get
  root 'customers#index'

  mount ResqueWeb::Engine => "/scheduler"
  ResqueWeb::Engine.eager_load!
end

app/models/rule.rb
# == Schema Information
#
# Table name: rules
#
#  id          :integer          not null, primary key
#  rule        :text
#  rule_body   :text
#  extra_var_1 :string(255)
#  extra_var_2 :string(255)
#  extra_var_3 :string(255)
#  customer_id :integer
#  name        :string(255)
#  rule_type   :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#  deliver_at  :string(255)
#  extra_var_4 :string(255)
#  state       :string(255)
#  subject     :string(255)
#

class Rule < ActiveRecord::Base
  belongs_to :customer

  state_machine :state, :initial => :inactive do
    state :active
    state :inactive

    event :activate do
      transition [:inactive, :active] => :active
    end

    event :deactivate do
      transition [:active, :inactive] => :inactive
    end
  end

  scope :active, -> { where(state: 'active').order(:id) }
  scope :inactive, -> { where(state: 'inactive').order(:id) }

  validates_presence_of :subject, if: Proc.new { |x| x.rule_type == 'Email' }

  # Determine the returned ruleset and merge to the rule body
  #
  # * Grab the rule query - loop and map the return
  #   to match what is needed in the sms table
  # * Build the accounting row for this batch
  # * Simply drop the accounting row and return if there is nothing to send

  def maps
    @uuid = UUID.new
    @temp_vars = declared
    @acct = Accounting.create(:customer_id => customer_id)
    rc = RemoteConnect.establish_connection customer.control.name.to_sym
    deliver = Merger::render_from_hash(deliver_at, {})
    erbified = Merger::render_from_hash(rule, {})
    remote_returns = rc.connection.execute(erbified)

    @acct.destroy && return if (remote_returns.present? && remote_returns.size == 0)
    return unless remote_returns.present?

    remote_returns.each do |s|
      if rule_type == 'SMS'
        sms_vars = combine_to_vars(s)
        to_sms(sms_vars, deliver)
      else
        email_vars = combine_to_vars(s)
        to_email(email_vars, deliver)
      end
    end
  end

  private

  # Determine the layout of the built sms
  #
  # * build and save the correctly laid out sms

  def to_sms(sms_vars, deliver)
    sms = Sms.new(:name => set_sms_name,
                  :customer_id => customer_id,
                  :to_deliver => deliver,
                  :repeat => 1,
                  :accounting => @acct,
                  :to_phone => sms_vars[:phone],
                  :body => Merger::render_from_hash(rule_body, sms_vars)
                 )
    sms.save if sms.valid?
  end

  # Determine the layout of the built email
  #
  # * build and save the correctly laid out email

  def to_email(email_vars, deliver)
    email = Email.new(:name => set_email_name,
                      :customer_id => customer_id,
                      :to_deliver => deliver,
                      :repeat => 1,
                      :accounting => @acct,
                      :to_email => email_vars[:email],
                      :subject => subject,
                      :body => Merger::render_from_hash(rule_body, email_vars)
                    )
    email.save if email.valid?
  end

  def set_sms_name
    u = @uuid.generate(:compact)[0..5].upcase
    "S#{u}"
  end

  def set_email_name
    e = @uuid.generate(:compact)[0..5].upcase
    "E#{e}"
  end


  def combine_to_vars(returns)
    current_vars = @temp_vars.dup
    current_vars.each do |k, v|
      current_vars[k] = returns[v]
    end
    current_vars
  end

  def declared
    h = {}
    inc = 0
    arr = [extra_var_1, extra_var_2, extra_var_3, extra_var_4].compact
    arr.each do |ex|
      h[ex.to_sym] = inc if ex.present?
      inc += 1 if ex.present?
    end
    h
  end

end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
load_and_authorize_resource
  before_action :set_rule, only: [:show, :edit, :update, :destroy]

  # GET /rules
  # GET /rules.json
  def index
    @rules = Rule.all
  end

  # GET /rules/1
  # GET /rules/1.json
  def show
  end

  # GET /rules/new
  def new
    @rule = Rule.new
  end

  # GET /rules/1/edit
  def edit
  end

  # POST /rules
  # POST /rules.json
  def create
    @rule = Rule.new(rule_params)
    @rule.rule.gsub!(/\r\n/,' ')

    respond_to do |format|
      if @rule.save
        format.html { redirect_to @rule, notice: 'Rule was successfully created.' }
        format.json { render action: 'show', status: :created, location: @rule }
      else
        format.html { render action: 'new' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rules/1
  # PATCH/PUT /rules/1.json
  def update
    respond_to do |format|
      rule_params[:rule].gsub!(/\r\n/,' ')
      if @rule.update(rule_params)
        format.html { redirect_to @rule, notice: 'Rule was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @rule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rules/1
  # DELETE /rules/1.json
  def destroy
    @rule.destroy
    respond_to do |format|
      format.html { redirect_to rules_url }
      format.json { head :no_content }
    end
  end

  def deactivate
    rule = Rule.find(params[:id])
    rule.deactivate!
    redirect_to rules_path
  end

  def activate
    rule = Rule.find(params[:id])
    rule.activate!
    redirect_to rules_path
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rule
      @rule = Rule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rule_params
      params.require(:rule).permit(:rule, :rule_body, :deliver_at, :extra_var_1, :extra_var_2, :extra_var_3, :extra_var_4, :extra_var_5, :subject, :customer_id, :name, :rule_type)
    end
end

app/helpers/rules_helper.rb
module RulesHelper
  def build_state_url(rule)
    if rule.active?
      "#{link_to "<b style='color:green;'>On</b>".html_safe, deactivate_rule_path(rule)}".html_safe
     else
      "#{link_to "<span style='color:red;'>Off</span>".html_safe, activate_rule_path(rule)}".html_safe
    end
  end
end

app/views/rules/_form.html.erb
<%= form_for(@rule) do |f| %>
  <% if @rule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rule.errors.count, "error") %> prohibited this rule from being saved:</h2>

      <ul>
      <% @rule.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%=h f.text_field :name, :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :rule %><br>
    <%= f.text_area :rule, :size => "50 x 10" %>
  </div>
  <div class="field">
    <%= f.label :rule_body %><br>
    <%= f.text_area :rule_body, :size => "50 x 10" %>
  </div>
  <div class="field">
    <%= f.label :to_deliver %><br>
    <%= f.text_area :deliver_at, :size => "50 x 1" %>
  </div>
  <div class="field">
    <%= f.label :extra_var_1 %><br>
    <%=h f.text_field :extra_var_1 %>
  </div>
  <div class="field">
    <%= f.label :extra_var_2 %><br>
    <%=h f.text_field :extra_var_2 %>
  </div>
    <%= f.label :extra_var_3 %><br>
    <%=h f.text_field :extra_var_3 %>
  </div>
  <div>
    <%= f.label :extra_var_4 %><br>
    <%=h f.text_field :extra_var_4 %>
  </div>
  <div>
    <%= f.label :extra_var_5 %><br>
    <%=h f.text_field :extra_var_5 %>
  </div>
  <div class="field">
    <%= f.label :subject %><br>
    <%=h f.text_field :subject, :size => 50 %>
  </div>
  <div class="field">
    <%= f.label :customer_id %><br>
    <%= f.number_field :customer_id %>
  </div>
  <div class="field">
    <%= f.label :rule_type %><br>
    <%= f.select :rule_type, [ 'SMS', 'Email' ] %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rules/edit.html.erb
<h1>Editing rule</h1>

<%= render 'form' %>

<%= link_to 'Show', @rule %> |
<%= link_to 'Back', rules_path %>

app/views/rules/index.html.erb
<h1>Rules</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Type</th>
      <th>Rule</th>
      <th>Body</th>
      <th>Deliver At</th>
      <th>Customer</th>
      <th>State</th>
      <th>Options</th>
    </tr>
  </thead>

  <tbody>
    <% @rules.each do |rule| %>
      <tr>
        <td><%=h rule.name %></td>
        <td><%=h rule.rule_type %></td>
        <td><%=h rule.rule[0..20] %>...</td>
        <td><%=h rule.rule_body[0..20] %>...</td>
        <td><%=h rule.deliver_at %></td>
        <td><%=h rule.customer.name %></td>
        <td><%= build_state_url(rule) %></td>
        <td><%= link_to 'View', rule %>
        <%= link_to 'Edit', edit_rule_path(rule) %>
        <%= link_to 'Remove', rule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rule', new_rule_path %></br/>
<%= link_to 'Controls', controls_path %></br/>
<%= link_to 'Customers', customers_path %><br/>
<%= link_to 'Scheduler', '/scheduler' %>

app/views/rules/new.html.erb
<h1>New rule</h1>

<%= render 'form' %>

<%= link_to 'Back', rules_path %>

app/views/rules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @rule.name %>
</p>

<p>
  <strong>Subject:</strong>
  <%= @rule.subject %>
</p>

<p>
  <strong>Rule:</strong>
  <%= @rule.rule %>
</p>

<p>
  <strong>Rule Body:</strong>
  <%= @rule.rule_body %>
</p>

<p>
  <strong>Deliver At:</strong>
  <%= @rule.deliver_at %>
</p>

<p>
  <strong>Extra 1:</strong>
  <%= @rule.extra_var_1 %>
</p>

<p>
  <strong>Extra 2:</strong>
  <%= @rule.extra_var_2 %>
</p>

<p>
  <strong>Extra 3:</strong>
  <%= @rule.extra_var_3 %>
</p>

<p>
  <strong>Extra 4:</strong>
  <%= @rule.extra_var_4 %>
</p>

<p>
  <strong>Extra 5:</strong>
  <%= @rule.extra_var_5 %>
</p>

<p>
  <strong>Customer:</strong>
  <%= @rule.customer_id %>
</p>

<p>
  <strong>Rule type:</strong>
  <%= @rule.rule_type %>
</p>

<%= link_to 'Edit', edit_rule_path(@rule) %> |
<%= link_to 'Back', rules_path %>